import data from './records.json';

/// Generated by scripts/sync-decisions.mjs from docs/decisions. Do not edit
/// records.json by hand; edit the markdown and re-run the script.
export type Kind = 'ADR' | 'GDR';
export type StatusKind = 'accepted' | 'proposed' | 'superseded';

export interface Relation {
	label: string;
	summary: string;
	refs: string[];
}

export interface DecisionRecord {
	id: string;
	kind: Kind;
	number: string;
	slug: string;
	path: string;
	title: string;
	status: string;
	statusKind: StatusKind;
	statusNote: string | null;
	supersededBy: string | null;
	supersedes: string[];
	date: string;
	relations: Relation[];
	excerpt: string;
	plain: string;
	html: string;
}

export const records = data as DecisionRecord[];

export function byId(id: string): DecisionRecord | undefined {
	const key = id.toUpperCase();
	return records.find((record) => record.id === key);
}
