import data from './launch.json';

/// Generated by scripts/sync-launch.mjs from docs/launch. Do not edit
/// launch.json by hand; edit the markdown and re-run the script.
export interface LaunchDoc {
	slug: string;
	path: string;
	title: string;
	intro: string;
	kind: string;
	status: string;
	order: number;
	copy: string | null;
	html: string;
}

export const launchDocs = data as LaunchDoc[];
