import data from './plans.json';

/// Generated by scripts/sync-plans.mjs from docs/plans. Do not edit
/// plans.json by hand; edit the markdown and re-run the script.
export interface Plan {
	slug: string;
	path: string;
	title: string;
	intro: string;
	date: string;
	order: number;
	done: number;
	open: number;
	html: string;
}

export const plans = data as Plan[];
