import data from './releases.json';

/// Generated by scripts/sync-releases.mjs from CHANGELOG.md. Do not edit
/// releases.json by hand; edit the changelog and re-run the script.
export interface ReleaseSection {
	name: string;
	html: string;
}

export interface Release {
	version: string;
	date: string | null;
	unreleased: boolean;
	url: string;
	intro: string;
	sections: ReleaseSection[];
	items: number;
}

export const releases = data as Release[];
export const shipped = releases.filter((r) => !r.unreleased);
export const next = releases.find((r) => r.unreleased) ?? null;
